server {
    listen 80;
    server_name thomian-lib.com;

    location / {
        proxy_pass http://localhost:3000; # Next.js Kiosk
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # API and Static/Media are also accessible here if needed
    location /api/ {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /var/www/thomian/static/;
    }

    location /media/ {
        alias /var/www/thomian/media/;
    }
}

server {
    listen 80;
    server_name admin.thomian-lib.com;

    root /var/www/thomian/main-app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
