# Generated by Django 6.0.2 on 2026-02-26 01:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('ddc_code', models.CharField(db_index=True, max_length=20)),
                ('classification', models.CharField(default='General', max_length=100)),
                ('call_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('barcode_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('shelf_location', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('pub_year', models.CharField(blank=True, max_length=4, null=True)),
                ('format', models.CharField(default='PAPERBACK', max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOANED', 'Loaned'), ('LOST', 'Lost'), ('PROCESSING', 'Processing'), ('HELD', 'Held')], default='AVAILABLE', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('marc_metadata', models.JSONField(default=dict)),
                ('material_type', models.CharField(default='REGULAR', max_length=50)),
                ('queue_length', models.IntegerField(blank=True, default=0, null=True)),
                ('last_inventoried', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('grade_level', models.CharField(blank=True, max_length=20, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('WORKSHOP', 'Workshop'), ('CLUB', 'Club'), ('EXAM', 'Exam'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('patron_group', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('LIBRARIAN', 'Librarian'), ('ADMINISTRATOR', 'Administrator')], max_length=20)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('fines', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pin', models.CharField(default='0000', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField(blank=True, null=True)),
                ('map_data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CirculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_group', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('LIBRARIAN', 'Librarian'), ('ADMINISTRATOR', 'Administrator')], max_length=20)),
                ('material_type', models.CharField(default='REGULAR', max_length=50)),
                ('loan_days', models.IntegerField(default=14)),
                ('max_items', models.IntegerField(default=5)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
            ],
            options={
                'unique_together': {('patron_group', 'material_type')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='backend.book')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='backend.patron')),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='backend.book')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='backend.patron')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('FINE_PAYMENT', 'Fine Payment'), ('REPLACEMENT_PAYMENT', 'Replacement Payment'), ('FINE_ASSESSMENT', 'Fine Assessment'), ('REPLACEMENT_ASSESSMENT', 'Replacement Assessment'), ('DAMAGE_ASSESSMENT', 'Damage Assessment'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('WAIVE', 'Waive')], max_length=30)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('SYSTEM', 'System')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('librarian_id', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('book_title', models.CharField(blank=True, max_length=255, null=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend.patron')),
            ],
        ),
    ]
